services:
  bitcoin-node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BITCOIN_VERSION: "29.0"
    container_name: infra-signet-docker
    command: tail -f /dev/null
    ports:
      - "38332:38332"  # RPC
      - "38333:38333"  # P2P
      - "38334:38334"  # P2P local
    environment:
      BITCOIN_VERSION: "29.0"
  bitcoin-miner:
    build:
      context: .
      dockerfile: Dockerfile.miner
      args:
        BITCOIN_VERSION: "29.0"
    container_name: bitcoin-miner
    command: tail -f /dev/null
    
    environment:

      BITCOIN_RPC_HOST: bitcoin-node
      BITCOIN_RPC_PORT: "38332"
      BITCOIN_VERSION: "29.0"
      

